import { NextRequest, NextResponse } from 'next/server'
import fs from 'fs'
import path from 'path'
import { localDb } from '@/lib/local-db'

/**
 * POST { local_path, type, session_id, event_name? }
 * Reads a file from the LOCAL DISK (C:/semeta/...) and uploads it to R2 via the Worker.
 * Designed for video _C.mp4 which is generated by FFmpeg locally — browser blob: URLs are
 * ephemeral and can't be relied on for upload. This route reads the actual file from disk,
 * bypassing the browser entirely.
 *
 * Also used for any other local file that needs to go to R2 (future: multi-AI local saves).
 */
export async function POST(req: NextRequest) {
  const workerUrl = process.env.NEXT_PUBLIC_WORKER_URL
  const secret = localDb.getSecret()
  if (!workerUrl || !secret)
    return NextResponse.json({ error: 'not configured' }, { status: 500 })

  const { local_path, type, session_id, event_name } = await req.json()
  if (typeof local_path !== 'string' || typeof type !== 'string' || typeof session_id !== 'string')
    return NextResponse.json({ error: 'local_path, type, session_id required' }, { status: 400 })

  // Security: only allow reading from C:/semeta/ to prevent path traversal
  const resolved = path.resolve(local_path)
  if (!resolved.toLowerCase().startsWith('c:\\semeta\\') && !resolved.toLowerCase().startsWith('c:/semeta/'))
    return NextResponse.json({ error: 'path must be under C:/semeta/' }, { status: 403 })

  if (!fs.existsSync(resolved))
    return NextResponse.json({ error: 'file not found' }, { status: 404 })

  const buf = fs.readFileSync(resolved)
  const ext = path.extname(resolved).toLowerCase()
  const mime = ext === '.mp4' ? 'video/mp4' : ext === '.jpg' || ext === '.jpeg' ? 'image/jpeg' : 'application/octet-stream'
  const blob = new Blob([buf], { type: mime })

  const form = new FormData()
  form.append('type', type)
  form.append('session_id', session_id)
  form.append('file', blob, path.basename(resolved))
  if (event_name) form.append('event_name', event_name)

  let res: Response
  try {
    res = await fetch(`${workerUrl}/api/upload`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${secret}` },
      body: form,
    })
  } catch (e) {
    const msg = e instanceof Error ? e.message : 'fetch failed'
    return NextResponse.json({ error: `worker unreachable: ${msg}` }, { status: 502 })
  }
  if (!res.ok) {
    const detail = await res.text().catch(() => '')
    console.error(`[upload-local-file] worker /api/upload ${res.status}: ${detail}`)
    return NextResponse.json(
      { error: 'upload failed', workerStatus: res.status, workerBody: detail.slice(0, 500) },
      { status: 502 },
    )
  }
  const data = await res.json()
  return NextResponse.json(data)
}
